### ISSUE TITLE
Failed at running Fly Registry Auth

### ISSUE THREAD

**Issue by felipsbreno** [kentcdodds/onewheel-blog#10]
I took this [course](https://egghead.io/courses/up-and-running-with-remix-b82b6bb6) with the aim of learning more about Remix. When sending a commit to git and running deploy.ci, an error occurs with the fly registry, the deploy.ci settings should be as shown in the image below?

![image](https://user-images.githubusercontent.com/50807243/202644193-f91bcf86-a67a-4141-a9dd-c52cc9858c38.png)

**Error:**

![image](https://user-images.githubusercontent.com/50807243/202645182-fe491455-c9bc-4ec7-840b-6916eadf094c.png)

Node version: `v16.14.2`
NPM version: `8.5.0`

**Comment by felipsbreno** [comment]
I looked the `deploy.yml` of project here and appears be equals.

![image](https://user-images.githubusercontent.com/50807243/202655569-9ace9f28-ec7a-4141-a0cd-8a015697e52c.png)

**Comment by kentcdodds** [comment]
Hi. Have you set the environment variable in your GitHub secrets?

**Comment by felipsbreno** [comment]
I added it here, is that right?

![image](https://user-images.githubusercontent.com/50807243/202759618-f39bd851-eff7-4346-a66b-76825a8475f0.png)

**Comment by kentcdodds** [comment]
No, that's not right. Watch this: https://egghead.io/lessons/remix-deploy-a-remix-application-to-fly-io
